config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :properties

  get 'about' => 'welcome#about'

  authenticated :user do
    root to: 'properties#index', as: :authenticated_root, via: :get
  end

  unauthenticated do
    root to: 'welcome#index'
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  has_many :tenants
  belongs_to :user

  mount_uploader :image, ImageUploader
  mount_uploader :file, FileUploader
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  belongs_to :property
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :properties

  before_create :set_default_role

  def admin?
    role == 'admin'
  end

  def property_manager?
    role == 'property_manager'
  end

  def tenant?
    role == 'tenant'
  end

  private

  def set_default_role
    self.role ||= 'property_manager'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def index
    @properties = current_user.properties
    authorize @properties
  end

  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
    authorize @property
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user
    authorize = @property
    if @property.save
      flash[:notice] = "Property was saved."
      redirect_to @property
    else
      flash[:error] = "There was an error saving the property. Please try again."
      render :new
    end
  end

  def edit
    @property = Property.find(params[:id])
    authorize @property
  end

  def update
    @property = Property.find(params[:id])
    authorize @property
    if @property.update_attributes(property_params)
      flash[:notice] = "Property was updated."
      redirect_to @property
    else
      flash[:error] = "There was an error saving the property. Please try again."
      render :edit
    end
  end
end

def property_params
  params.require(:property).permit(:name, :address1, :address2, :address3, :country, :city, :state, :zip, :taxes, :rent, :notes, :image, :file)
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rent2me</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Rent2Me", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right user-info">
        <% if current_user %>
        Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

  <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>

    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %> 
     
    <%= yield %>
    </div>
    
  </body>
</html>

app/views/properties/_property.html.erb
<%= content_tag :tr, id: "property-#{property.id}" do %>
  <td><%= @property.name %></td>
  <td><%= @property.address1 %></td>
  <td><%= @property.address2 %></td>
  <td><%= @property.address3 %></td>
  <td><%= @property.country %></td>
  <td><%= @property.city %></td>
  <td><%= @property.state %></td>
  <td><%= @property.zip %></td>
  <td><%= @property.taxes %></td>
  <td><%= @property.rent %></td>
  <td><%= @property.notes %></td>
  <td><%= @property.file %></td>
<% end %>

app/views/properties/edit.html.erb
<h1>Edit Property</h1>
<div class="row">
  <div class="col-md-12">
    <%= form_for @property do |f| %>
      <% if @property.image? %>
        <div class="form-group">
          <p>Current Image</p>
          <%= image_tag ( @property.image.show.url ) %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :address1 %>
        <%= f.text_field :address1%>
      </div>
      <div class="form-group">
        <%= f.label :address2 %>
        <%= f.text_field :address2 %>
      </div>
      <div class="form-group">
        <%= f.label :address3 %>
        <%= f.text_field :address3 %>
      </div>
      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>
      <div class="form-group">
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>
      <div class="form-group">
        <%= f.label :taxes %>
        <%= f.text_field :taxes %>
      </div>
      <div class="form-group">
        <%= f.label :rent %>
        <%= f.text_field :rent %>
      </div>
      <div class="form-group">
        <%= f.label :notes %>
        <%= f.text_field :notes %>
      </div>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    </div>
  <% end %>
</div>

app/views/properties/index.html.erb
<div class="row">
  <div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#properties" data-toggle="tab">Property Management</a></li>
      <li><a href="#tenant" data-toggle="tab">Tenant Management</a></li>
      <li><a href="#repairs" data-toggle="tab">Repair Requests</a></li>
      <li><a href="#messages" data-toggle="tab">Messages</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="properties">
        <h1>Properties</h1>
        <% if policy(Property.new).create? %>
          <%= link_to "New Property", new_property_path, class: 'btn btn-success' %>
        <% end %>
        <br>
        <div class="row">
          <div class="col-md-8">
            <% @properties.each do |property| %>
              <div class="media">
                <div class="media-body">
                  <h4 class="media-heading">
                    <%= link_to property.name, property %>
                  </h4>
                  <small>
                    <%= image_tag (property.image.tiny.url) if property.image? %>
                    <%= property.address1 %>
                    <%= property.city %>,
                    <%= property.state %>
                    <%= property.zip %>
                  </small>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tab-pane" id="tenant">
        <p>This is where the full tenant list will appear</p>
      </div>
      <div class="tab-pane" id="repairs">
        <p>This is where the full repair request list will appear for all properties</p>
      </div>
      <div class="tab-pane" id="messages">
        <p>This is where messaging between users will be implemented</p>
      </div>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
<h1>New Property</h1>
<div class="row">
  <div class="col-md-12">
    <%= form_for @property do |f| %>
      <% if @property.image? %>
        <div class="form-group">
          <p>Current Image</p>
          <%= image_tag ( @property.image.show.url ) %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
        <%= f.hidden_field :image_cache %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :address1 %>
        <%= f.text_field :address1%>
      </div>
      <div class="form-group">
        <%= f.label :address2 %>
        <%= f.text_field :address2 %>
      </div>
      <div class="form-group">
        <%= f.label :address3 %>
        <%= f.text_field :address3 %>
      </div>
      <div class="form-group">
        <%= f.label :country %>
        <%= f.text_field :country %>
      </div>
      <div class="form-group">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div class="form-group">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>
      <div class="form-group">
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>
      <div class="form-group">
        <%= f.label :taxes %>
        <%= f.text_field :taxes %>
      </div>
      <div class="form-group">
        <%= f.label :rent %>
        <%= f.text_field :rent %>
      </div>
      <div class="form-group">
        <%= f.label :notes %>
        <%= f.text_field :notes %>
      </div>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    </div>
  <% end %>
</div>

app/views/properties/show.html.erb
<div class="row">
  <div class="tabbable tabs-left">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#general" data-toggle="tab">General</a></li>
      <li><a href="#files" data-toggle="tab">Lease</a></li>
      <li><a href="#tenants" data-toggle="tab">Tenants</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="general">
        <h1><%= @property.name %></h1>
        <% if policy(@property).edit? %>
          <%= link_to "Edit", edit_property_path(@property), class: 'btn btn-success' %>
        <% end %>
        <p><%= image_tag (@property.image.show.url) if @property.image? %></p>
        <p><strong>Address 1</strong>: <%= @property.address1 %></p>
        <p><strong>Address 2</strong>: <%= @property.address2 %></p>
        <p><strong>Address 3</strong>: <%= @property.address3 %></p>
        <p><strong>City</strong>: <%= @property.city %></p>
        <p><strong>State</strong>: <%= @property.state %></p>
        <p><strong>Zip</strong>: <%= @property.zip %></p>
        <p><strong>Country</strong>: <%= @property.country %></p>
        <p><strong>Taxes</strong>: <%= @property.taxes %></p>
        <p><strong>Rent</strong>: <%= @property.rent %></p>
        <p><strong>Notes</strong>: <%= @property.notes %></p>
      </div>
      <div class="tab-pane" id="files">
        <%= form_for @property, html: { multipart: true } do |f| %>
          <p>
            <label>Property Lease</label>
            <br>
            <%= f.file_field :file %>
            <%= f.hidden_field :file_cache %>
            <%= f.submit "Upload Lease", class: 'btn btn-primary' %>
          </p>
        <% end %>
        <table class="table table-bordered table-striped">  <thead>
            <tr>
              <th>Lease File</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td><%= link_to @property.file_name, @property.file_url %></td>
              </tr>
          </tbody>
        </table>
      </div>
      <div class="tab-pane" id="tenants">
        <p>This is where tenants for the property will show</p>
      </div>
    </div>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>About Rent2Me</h1>
<p>A tech startup providing SaaS for property owners allowing them to manage their properties and tenants easily online.</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Rent2Me</h1>
  <p>An application for property owners/managers allowing you to manage your properties and tenants easily online!</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Manage Properties</h2>
    <p>Keep track of all of your properties in one place. Keep track of your repair and taxes to see how profitable your properties really are.</p>
  </div>
  <div class="col-md-4">
    <h2>Manage Tenants</h2>
    <p>Keep track of your clients to make sure you are getting your rent on time!</p>
  </div>
  <div class="col-md-4">
    <h2>Get your Rent Quicker!</h2>
    <p>With our Stripe Integration, you will be able to get your rent quicker than ever. No more waiting for snail mail to receive your rent checks!</p>
  </div>
</div>